/**
 * `jentrix artifact register --paths a,b,…` — R04 (opencode-pi-plugins PRD
 * §4.1, finding 4): the BOUNDED OUTPUT MANIFEST.
 *
 * The audit found native outputs (a PDF, a screenshot, a generated bundle)
 * either missing from the record or coerced through the UTF-8 Markdown push.
 * This registers each declared file through the SAME upload-grant core the
 * single `artifact upload` command uses (bytes preserved, sha256-bound, MIME
 * from the extension), then pushes ONE attested REPORT — the manifest — whose
 * `output-manifest` header lists every entry with path, MIME, size, checksum,
 * the artifact it landed as (or why it did not), and the producing
 * session/task and repository revision. Bounded: at most
 * {@link MAX_MANIFEST_ENTRIES} paths; a missing or unreadable path REFUSES the
 * whole command before anything uploads — a manifest that silently drops a
 * declared output is the defect this exists to end.
 */

import { existsSync, statSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";

import { Command } from "commander";

import { EXIT_CODES } from "../errors";
import { defaultGitRunner, inspectRepository } from "../repo";
import { renderSemanticHeader } from "../session-host/semantic-header";
import { readAlignmentMarker } from "../session/state";
import { readCurrentProviderHookContext } from "../session/provider-context";
import { callStructured, UsageError } from "../tool-client";
import { ArtifactAttachError, attachFile } from "./artifact";
import { runPush, scopedDirtyDigest, type PushDeps } from "./push";

export const MAX_MANIFEST_ENTRIES = 50;

export interface ArtifactRegisterFlags {
  paths?: string;
  session?: string;
  task?: string;
  title?: string;
  json?: boolean;
}

export interface ManifestEntry {
  path: string;
  filename: string;
  mimeType: string;
  byteSize: number;
  checksum: string | null;
  artifactId: string | null;
  artifactType: string | null;
  uploadStatus: "uploaded" | "failed";
  error?: string;
}

/** Split `--paths` on commas/newlines, trim, drop empties, de-duplicate. */
export function parsePaths(raw: string | undefined): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const piece of (raw ?? "").split(/[,\n]/)) {
    const path = piece.trim();
    if (!path || seen.has(path)) continue;
    seen.add(path);
    out.push(path);
  }
  return out;
}

/** The manifest body: header first (R08), then the human table. */
export function renderManifest(input: {
  entries: ManifestEntry[];
  sessionId: string | null;
  taskId: string | null;
  revision: string | null;
  dirtyDigest: string | null;
  generatedAt: string;
}): string {
  const uploaded = input.entries.filter((e) => e.uploadStatus === "uploaded").length;
  const header = renderSemanticHeader({
    kind: "output-manifest",
    producer: "cli",
    generatedAt: input.generatedAt,
    ...(input.sessionId ? { sessionId: input.sessionId } : {}),
    ...(input.taskId ? { taskId: input.taskId } : {}),
    ...(input.revision ? { revision: input.revision } : {}),
    ...(input.dirtyDigest ? { dirtyDigest: input.dirtyDigest } : {}),
    count: input.entries.length,
    uploaded,
    failed: input.entries.length - uploaded,
    entries: input.entries.map((e) => ({
      path: e.path,
      mimeType: e.mimeType,
      byteSize: e.byteSize,
      checksum: e.checksum,
      artifactId: e.artifactId,
      artifactType: e.artifactType,
      uploadStatus: e.uploadStatus,
      ...(e.error ? { error: e.error } : {}),
    })),
  });
  const rows = input.entries.map(
    (e) =>
      `| \`${e.path}\` | ${e.mimeType} | ${e.byteSize} | ${e.checksum ? e.checksum.slice(0, 12) + "…" : "—"} | ${e.uploadStatus === "uploaded" ? `artifact ${e.artifactId} (${e.artifactType})` : `FAILED — ${e.error ?? "unknown"}`} |`,
  );
  return [
    header,
    "",
    `# Output manifest — ${uploaded}/${input.entries.length} file(s) registered`,
    "",
    `Generated by \`jentrix artifact register\` at ${input.generatedAt}${input.revision ? ` · revision ${input.revision.slice(0, 10)}${input.dirtyDigest ? " (dirty tree)" : ""}` : ""}. Bytes were uploaded through the upload-grant path (binary-safe, sha256-bound); the checksum below is of the file as read on this machine.`,
    "",
    "| Path | MIME | Bytes | sha256 | Landed as |",
    "|------|------|-------|--------|-----------|",
    ...rows,
    ...(uploaded < input.entries.length
      ? ["", `${input.entries.length - uploaded} declared output(s) did NOT upload — each row names why; the manifest is complete about what is missing.`]
      : []),
  ].join("\n");
}

export async function runArtifactRegister(
  flags: ArtifactRegisterFlags,
  deps: PushDeps,
): Promise<number> {
  try {
    const paths = parsePaths(flags.paths);
    if (paths.length === 0) throw new UsageError("--paths <a,b,…> names at least one file to register");
    if (paths.length > MAX_MANIFEST_ENTRIES) {
      throw new UsageError(`--paths names ${paths.length} files; the manifest is bounded at ${MAX_MANIFEST_ENTRIES} — register the rest in a second manifest`);
    }
    if (flags.session && flags.task) throw new UsageError("pass --session or --task, not both");
    const cwd = deps.cwd();
    for (const path of paths) {
      const abs = resolve(cwd, path);
      if (!existsSync(abs) || !statSync(abs).isFile()) {
        throw new UsageError(`${path} is not a readable file — every declared output must exist before the manifest is written`);
      }
    }

    // Addressing: an explicit --session/--task, else THIS provider session's
    // alignment marker (never a neighbour's). The uploads need the task; a
    // session-level alignment (no task) uploads against the workspace.
    const inspection = await inspectRepository(cwd, deps.git);
    let sessionId: string | null = flags.session ?? null;
    let taskId: string | null = flags.task ?? null;
    let workspaceId: string | null = null;
    if (!sessionId && !taskId) {
      if (!inspection) throw new UsageError("the current directory is not inside a git work tree — run from the aligned checkout, or pass --session <id> or --task <id>");
      const marker = readAlignmentMarker(deps.configPath, inspection.root, readCurrentProviderHookContext(deps)?.sessionId ?? null);
      if (!marker) throw new UsageError("this session has no alignment — run `jentrix session align --task <id-or-key>` first, or pass --session <id> or --task <id>");
      sessionId = marker.sessionId;
      taskId = marker.taskId;
      workspaceId = marker.workspaceId;
    }
    // An explicit --session places the uploads on THAT session's aligned task
    // (or its workspace, for session-level work) — read from the server, never
    // guessed. The M1 Codex trial hit the earlier refusal here.
    if (sessionId && !taskId && !workspaceId) {
      const { caller, close } = await deps.connect({ ...deps.resolveTarget(), sessionId });
      try {
        const row = await callStructured(caller, "get_agent_session", { sessionId });
        taskId = typeof row.taskId === "string" ? row.taskId : null;
        workspaceId = typeof row.workspaceId === "string" ? row.workspaceId : null;
      } finally {
        await close().catch(() => undefined);
      }
    }
    if (!taskId && !workspaceId) {
      throw new UsageError("--session alone cannot place the files: the session names no task or workspace — pass --task <id>");
    }

    const entries: ManifestEntry[] = [];
    for (const path of paths) {
      const abs = resolve(cwd, path);
      const shown = inspection ? relative(inspection.root, abs) || path : path;
      try {
        const attached = await attachFile(
          abs,
          {
            ...(taskId ? { task: taskId } : {}),
            ...(!taskId && workspaceId ? { workspace: workspaceId } : {}),
            ...(sessionId ? { session: sessionId } : {}),
            title: shown,
          },
          deps,
        );
        entries.push({
          path: shown,
          filename: attached.filename,
          mimeType: attached.mimeType,
          byteSize: attached.byteSize,
          checksum: attached.checksum,
          artifactId: attached.artifactId || null,
          artifactType: attached.type,
          uploadStatus: attached.artifactId ? "uploaded" : "failed",
          ...(attached.artifactId ? {} : { error: "attach_artifact returned no id" }),
        });
        deps.writeOut(`registered ${shown} → artifact ${attached.artifactId || "?"} (${attached.type}, ${attached.byteSize} bytes, sha256 ${attached.checksum.slice(0, 12)}…)`);
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        const size = statSync(abs).size;
        entries.push({
          path: shown,
          filename: abs.split("/").pop() ?? shown,
          mimeType: "application/octet-stream",
          byteSize: size,
          checksum: null,
          artifactId: null,
          artifactType: null,
          uploadStatus: "failed",
          error: message,
        });
        deps.writeErr(`note: ${shown} did NOT upload (${message}) — recorded as failed in the manifest`);
        if (!(error instanceof ArtifactAttachError)) throw error;
      }
    }

    const dirtyDigest = inspection?.dirty
      ? await scopedDirtyDigest(deps.git ?? defaultGitRunner, inspection.root).catch(() => null)
      : null;
    const body = renderManifest({
      entries,
      sessionId,
      taskId,
      revision: inspection?.head ?? null,
      dirtyDigest,
      generatedAt: new Date().toISOString(),
    });
    // The manifest rides the ordinary typed push (redaction, addressing, the
    // issue-mint offer, `--json`) as an ATTESTED report: the CLI wrote every
    // byte of it from what it just uploaded.
    const scratch = mkdtempSync(join(tmpdir(), "jentrix-manifest-"));
    const file = join(scratch, "output-manifest.md");
    try {
      writeFileSync(file, body);
      const code = await runPush(
        "report",
        file,
        {
          title: flags.title ?? `Output manifest — ${entries.filter((e) => e.uploadStatus === "uploaded").length}/${entries.length} file(s)`,
          ...(flags.session ? { session: flags.session } : {}),
          ...(flags.task ? { task: flags.task } : {}),
          ...(flags.json ? { json: true } : {}),
          attested: true,
        },
        deps,
      );
      if (code !== 0) return code;
      return entries.every((e) => e.uploadStatus === "uploaded") ? 0 : EXIT_CODES.INTERNAL;
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
  } catch (error) {
    if (error instanceof UsageError) {
      deps.writeErr(error.message);
      return EXIT_CODES.INVALID_INPUT;
    }
    throw error;
  }
}

export function registerArtifactRegisterCommand(
  artifact: Command,
  deps: PushDeps,
  onExit: (code: number) => void,
): void {
  artifact
    .command("register")
    .description(
      `Register declared output files (binary-safe, via upload grants) and push ONE attested output manifest naming each file's path, MIME, size, sha256 and the artifact it landed as. Bounded at ${MAX_MANIFEST_ENTRIES} paths; a missing file refuses the whole command.`,
    )
    .requiredOption("--paths <a,b,…>", "comma-separated file paths (relative to the current directory)")
    .option("--session <id>", "address the manifest to a specific session (default: this session's alignment)")
    .option("--task <id>", "address the manifest and uploads to a task (no session)")
    .option("--title <title>", "manifest title")
    .option("--json", "stable JSON output")
    .action(async (flags: ArtifactRegisterFlags) => onExit(await runArtifactRegister(flags, deps)));
}
