/** Session end. */
import { EXIT_CODES } from "../errors";
import { type GitRunner, inspectRepository, defaultGitRunner } from "../repo";
import { type SessionCommandDeps } from "./deps";
import { stacksBaseUrlOf, withCaller, reportError } from "./runtime";
import { createSessionRedactor } from "../session-host/session-redact";
import { readCurrentProviderHookContext } from "./provider-context";
import { readAlignmentMarker, clearAlignmentMarker } from "./state";
import { activeSessionsBoundHere, telemetryVerdict } from "./status";
import {
  hasLocalCaptureFootprint,
  readLiveHostMarker,
  clearEndRefusal,
  waitForHostEnd,
} from "./host-control";
import { callStructured as call, UsageError } from "../tool-client";
import { writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * PURE close verdict (AGE-965). A successful close and a failed close used to
 * share exit 1 whenever capture was incomplete, so a script could not tell
 * "closed, with a recorded gap" from "the close did not happen". The gap gets
 * its own code; real failures keep theirs (they never reach here — they throw).
 *
 * `captureStatus` (AGE-958, on BOTH `get_agent_session` and
 * `complete_agent_session`) is the server's own derived verdict and the field
 * a `--json` consumer should read; `captureComplete` + the alignment's capture
 * mode stay the fallback for a server that predates it.
 */
export function sessionCloseVerdict(
  row: { captureStatus?: unknown; captureComplete?: unknown },
  offByDesign: boolean,
): { code: number; capture: string } {
  const status =
    typeof row.captureStatus === "string" ? row.captureStatus : null;
  if (status === "OFF_BY_DESIGN" || (status === null && offByDesign)) {
    // Capture-off is a deliberate mode, never capture debt.
    return { code: EXIT_CODES.OK, capture: "off (typed artifacts only)" };
  }
  const complete =
    status !== null ? status === "COMPLETE" : Boolean(row.captureComplete);
  return complete
    ? { code: EXIT_CODES.OK, capture: "complete" }
    : {
        code: EXIT_CODES.CAPTURE_INCOMPLETE,
        capture: "INCOMPLETE (recorded)",
      };
}

/** Session evidence floor (PRD §5): the attested-delivery patch cap. */
export const MAX_ATTESTED_DIFF_BYTES = 256 * 1024;

/**
 * Build the attested delivery body for `startHead..endHead` — the REAL git
 * patch, generated by the CLI from the aligned checkout (D4: the server never
 * runs git). Truncates STAT-FIRST: when the full `--patch --stat` output
 * exceeds the 256 KB cap (or git refuses it), the body keeps the commit list
 * + per-file stat and DECLARES the cut. Returns null when the range holds no
 * commits.
 *
 * JEN-171 — the body is a PURE FUNCTION OF THE RANGE. It used to append the
 * dirty tree's uncommitted-delta stat, which is the one part that is not
 * about the attested range at all: between a refused `session end` and its
 * comply-and-retry the working tree moves, the regenerated body differed, and
 * the server's content-identity dedupe correctly saw two artifacts — one
 * range, two attested DIFFs. The stat comes back as `uncommitted` so the end
 * command can still SAY it; the durable dirty fact is the RUN_SUMMARY's own
 * `repo delta: … dirty: true`.
 */
export async function buildAttestedDiffBody(
  git: GitRunner,
  root: string,
  startHead: string,
  endHead: string,
  dirty: boolean,
): Promise<{
  body: string;
  commitCount: number;
  uncommitted: string | null;
} | null> {
  const counted = await git(
    ["rev-list", "--count", `${startHead}..${endHead}`],
    root,
  );
  if (counted.code !== 0) return null;
  const commitCount = Number(counted.stdout.trim());
  if (!Number.isFinite(commitCount) || commitCount === 0) return null;
  const header = [
    "Attested delivery — generated by `jentrix session end` from the aligned checkout (source: cli).",
    `Range: ${startHead}..${endHead} · ${commitCount} commit(s)`,
    "",
  ].join("\n");
  const cap = MAX_ATTESTED_DIFF_BYTES - Buffer.byteLength(header, "utf8");
  const full = await git(
    ["log", "--patch", "--stat", `${startHead}..${endHead}`],
    root,
  );
  let body: string;
  if (full.code === 0 && Buffer.byteLength(full.stdout, "utf8") <= cap) {
    body = full.stdout;
  } else {
    const stat = await git(["log", "--stat", `${startHead}..${endHead}`], root);
    const notice =
      "[truncated stat-first: the full --patch output exceeded the 256 KB attested-diff cap — commit list + per-file stat retained; the full patch lives in git]\n\n";
    let kept = stat.code === 0 ? stat.stdout : "(git log --stat failed)";
    const room = cap - Buffer.byteLength(notice, "utf8");
    if (Buffer.byteLength(kept, "utf8") > room) {
      kept =
        Buffer.from(kept, "utf8")
          .subarray(0, Math.max(0, room - 64))
          .toString("utf8")
          .replace(/�+$/, "") + "\n[stat tail truncated at the cap]";
    }
    body = notice + kept;
  }
  let uncommitted: string | null = null;
  if (dirty) {
    const delta = await git(["diff", "--stat", "HEAD"], root);
    uncommitted =
      delta.code === 0 && delta.stdout.trim() ? delta.stdout.trim() : null;
  }
  return { body: header + body, commitCount, uncommitted };
}

/**
 * POST an ATTESTED typed artifact (D4) to the session's push boundary —
 * redacted locally like every push, `attested: true` so it lands with
 * `source: "cli"`. Best-effort by design: a failed push is reported and the
 * E1 check refuses the close honestly rather than this throwing.
 */
async function postAttestedArtifact(
  deps: SessionCommandDeps,
  sessionId: string,
  input: { kind: "diff" | "log"; title: string; body: string },
): Promise<{ ok: boolean; artifactId: string | null; detail: string | null }> {
  const credentials = deps.resolveTarget();
  try {
    const response = await (deps.fetchImpl ?? fetch)(
      new URL(
        `/api/agent-sessions/${sessionId}/artifacts`,
        stacksBaseUrlOf(credentials.url),
      ),
      {
        method: "POST",
        headers: {
          authorization: `Bearer ${credentials.token}`,
          "content-type": "application/json",
        },
        body: JSON.stringify({
          kind: input.kind,
          title: input.title,
          body: createSessionRedactor({ env: deps.env }).text(input.body),
          attested: true,
        }),
      },
    );
    const payload = (await response.json().catch(() => ({}))) as {
      artifactId?: string;
      error?: string;
      detail?: string;
    };
    return response.ok
      ? { ok: true, artifactId: payload.artifactId ?? null, detail: null }
      : {
          ok: false,
          artifactId: null,
          detail: payload.detail ?? payload.error ?? `HTTP ${response.status}`,
        };
  } catch (error) {
    return {
      ok: false,
      artifactId: null,
      detail: error instanceof Error ? error.message : "network failure",
    };
  }
}

export async function runSessionEnd(
  sessionIdFlag: string | undefined,
  flags: { json?: boolean; acknowledgeEvidenceGaps?: boolean },
  deps: SessionCommandDeps,
): Promise<number> {
  try {
    const inspection = await inspectRepository(deps.cwd(), deps.git);
    return await withCaller(deps, async (caller) => {
      // AGE-958: bare `session end` resolves the CURRENT session the same way
      // `jentrix push` does — THIS provider session's alignment marker for this
      // checkout. Keyed by the asking session, because a checkout can hold
      // several open sessions at once and closing the newest one instead of
      // your own is not a bare `end`, it is someone else's. AGE-963: the
      // marker is VERIFIED against the server first — a stale marker (session
      // already ended) is reaped and never shadows the live session, and with
      // no usable marker the ACTIVE session this machine bound to this
      // checkout is the fallback.
      const ownThread = readCurrentProviderHookContext(deps)?.sessionId ?? null;
      let resolved = sessionIdFlag;
      if (!resolved && inspection) {
        const marker = readAlignmentMarker(
          deps.configPath,
          inspection.root,
          ownThread,
        );
        if (marker) {
          let markerStatus: string | null = null;
          try {
            const s = await call(caller, "get_agent_session", {
              sessionId: marker.sessionId,
            });
            markerStatus = String(s.status);
          } catch {
            markerStatus = null;
          }
          if (markerStatus === "ACTIVE" || markerStatus === "STARTING") {
            resolved = marker.sessionId;
            deps.writeOut(
              `Ending the aligned session for this checkout: ${resolved}`,
            );
          } else {
            clearAlignmentMarker(
              deps.configPath,
              inspection.root,
              marker.sessionId,
            );
            deps.writeOut(
              `Stale alignment marker cleared (session ${marker.sessionId} ${markerStatus ? `is ${markerStatus}` : "is no longer readable"}).`,
            );
          }
        }
        if (!resolved && inspection.repoOwnerName) {
          const all = await activeSessionsBoundHere(
            caller,
            deps,
            inspection.repoOwnerName,
          );
          // This provider thread's own session wins outright when the server
          // knows one — that is the session the caller is sitting in, however
          // many others share the checkout.
          const own = ownThread
            ? all.filter((s) => s.providerSessionId === ownThread)
            : [];
          const bound = own;
          if (bound.length === 1) {
            resolved = bound[0].id;
            deps.writeOut(`Ending this session: ${resolved}`);
          } else if (ownThread && bound.length > 1) {
            throw new UsageError(
              `several active sessions are bound to this checkout — pass one id to \`jentrix session end <id>\`: ${bound.map((s) => s.id).join(", ")}`,
            );
          } else if (!ownThread && all.length > 0) {
            throw new UsageError(
              "no trusted provider session identifies the caller — pass one id to `jentrix session end <id>`",
            );
          }
        }
      }
      if (!resolved) {
        throw new UsageError(
          "pass the Jentrix session id to end — no aligned session marker for this checkout (run `jentrix session align --task <id-or-key>` first, or find the id with `jentrix session status`, `jentrix agent list-sessions --workspace <id>`, or the workspace's Sessions page)",
        );
      }
      const sessionId: string = resolved;
      // Evidence floor (PRD §5): when HEAD moved in the aligned checkout,
      // generate and push the ATTESTED delivery patch BEFORE anything closes
      // — the E1 check server-side keys on its existence. Best-effort: a
      // failed push is disclosed and the close's refusal names the gap.
      let commitCount: number | null = null;
      try {
        const row = await call(caller, "get_agent_session", { sessionId });
        const startHead =
          typeof row.startHead === "string" ? row.startHead : null;
        const attestRepo =
          inspection && inspection.repoOwnerName === row.repoOwnerName
            ? inspection
            : null;
        if (
          attestRepo?.head &&
          startHead &&
          attestRepo.head !== startHead &&
          (row.status === "ACTIVE" || row.status === "STARTING")
        ) {
          const built = await buildAttestedDiffBody(
            deps.git ?? defaultGitRunner,
            attestRepo.root,
            startHead,
            attestRepo.head,
            attestRepo.dirty,
          );
          if (built) {
            commitCount = built.commitCount;
            const pushed = await postAttestedArtifact(deps, sessionId, {
              kind: "diff",
              title: `Attested diff ${startHead.slice(0, 10)}..${attestRepo.head.slice(0, 10)} (${built.commitCount} commit${built.commitCount === 1 ? "" : "s"})`,
              body: built.body,
            });
            if (pushed.ok) {
              deps.writeOut(
                `Attested diff pushed → artifact ${pushed.artifactId ?? "(unknown)"} (${built.commitCount} commit(s), source: cli)`,
              );
              // JEN-171: said, never embedded. The uncommitted delta is real
              // and worth knowing at close, but it is not part of the range
              // the artifact attests — inside the body it made a retry after
              // any tree churn push a SECOND DIFF for the same range.
              if (built.uncommitted) {
                deps.writeOut(
                  `note: uncommitted delta at end (stat only — not part of the attested range):\n${built.uncommitted}`,
                );
              }
            } else {
              deps.writeErr(
                `note: attested diff push failed (${pushed.detail}) — the E1 delivery check will refuse the close; retry \`jentrix session end\`, or acknowledge with --acknowledge-evidence-gaps.`,
              );
            }
          }
        }
      } catch {
        // Unreadable session/repo state: the server's checks stay the truth.
      }
      /**
       * F1c/F3 + F4: the closing telemetry is the session's most important
       * closing fact AND the one that silently fails, so `end` states it on
       * every path — including the one that returns early. `/jentrix-end` can
       * then report a real number (or a named gap) instead of inferring
       * success from exit 0, which is exactly what went wrong on 2026-08-11.
       * Reported AFTER the close line so the JSON payload stays first.
       */
      const hostRan = hasLocalCaptureFootprint(deps, sessionId);
      const reportTelemetry = (row: Record<string, unknown>): void => {
        const verdict = telemetryVerdict(
          sessionId,
          row.usage,
          hostRan,
          row.provider === "codex" ? "codex" : "claude",
        );
        // Under --json stdout stays ONE parseable document (the payload
        // already carries `usage`); the warning is stderr on both paths.
        if (!flags.json) deps.writeOut(verdict.line);
        if (verdict.warning) deps.writeErr(verdict.warning);
      };
      // A LIVE local host owns the spool and the manifest — hand it the end
      // request and report ITS verdict instead of racing it with a direct
      // server-side completion that would find parts still unflushed.
      const live = readLiveHostMarker(deps, sessionId);
      if (live) {
        // A refusal from an EARLIER end must never answer this one.
        clearEndRefusal(deps, sessionId);
        writeFileSync(
          join(deps.spoolRoot, sessionId, "end-request.json"),
          JSON.stringify({
            requestedAt: new Date().toISOString(),
            // JEN-167: the host closes the session, so the operator's
            // acknowledgement has to travel with the request — otherwise the
            // floor refuses a close they explicitly asked to force. The
            // CLI-counted commits ride along for the same reason: only the
            // CLI can count them, and the host's close is the one that lands.
            ...(flags.acknowledgeEvidenceGaps
              ? { acknowledgeEvidenceGaps: true }
              : {}),
            ...(commitCount !== null ? { commitCount } : {}),
          }),
          { mode: 0o600 },
        );
        deps.writeOut(
          `Local capture host (pid ${live.pid}) is finalizing capture…`,
        );
        const outcome = await waitForHostEnd(deps, sessionId, live.pid, 90_000);
        if (outcome.kind === "refused") {
          // JEN-167: the floor refused and the host SURVIVED it — the session
          // is untouched and still recording. Relay the envelope verbatim
          // (reportError adds the acknowledge hint and exits 5) and never
          // complete server-side over a living host.
          deps.writeErr(
            `local capture host (pid ${live.pid}) is still running — the skeleton, heartbeats and telemetry keep accumulating through the comply work; re-run \`jentrix session end ${sessionId}\` once the evidence is pushed`,
          );
          throw new Error(outcome.message);
        }
        if (outcome.kind === "exited") {
          const final = await call(caller, "get_agent_session", { sessionId });
          const stillOpen =
            final.status === "STARTING" || final.status === "ACTIVE";
          if (!stillOpen) {
            if (inspection) {
              clearAlignmentMarker(deps.configPath, inspection.root, sessionId);
            }
            const verdict = sessionCloseVerdict(
              final,
              (final.alignment as { capture?: string } | null)?.capture ===
                "off",
            );
            deps.writeOut(
              flags.json
                ? JSON.stringify(final)
                : `Session ${sessionId} closed · capture ${verdict.capture} · summary ${final.summaryArtifactId ? String(final.summaryArtifactId) : "—"}`,
            );
            reportTelemetry(final);
            return verdict.code;
          }
          // The host exited but could not close the session (dead bearer,
          // crash mid-finalize) — never report "closed" over an open session.
          deps.writeErr(
            `local capture host (pid ${live.pid}) exited without completing the session — completing server-side; the local spool is retained`,
          );
        } else {
          deps.writeErr(
            `local capture host (pid ${live.pid}) did not finalize in time — completing server-side; the local spool is retained for retry`,
          );
        }
      }
      const session = await call(caller, "get_agent_session", { sessionId });
      const sameRepo =
        inspection?.repoOwnerName === session.repoOwnerName ? inspection : null;
      // Durable-telemetry fallback (2026-08-08): a host that died before
      // completing leaves its last provider-receipt rollup in the spool —
      // submit that instead of closing the session with null usage.
      let spooledUsage: Record<string, unknown> | undefined;
      try {
        const snapshot = JSON.parse(
          readFileSync(join(deps.spoolRoot, sessionId, "usage.json"), "utf8"),
        ) as { rollup?: Record<string, unknown> };
        const rollup = snapshot?.rollup;
        if (rollup && typeof rollup === "object") {
          spooledUsage = {
            inputTokens: rollup.inputTokens,
            outputTokens: rollup.outputTokens,
            cacheReadTokens: rollup.cacheReadTokens,
            cacheCreationTokens: rollup.cacheCreationTokens,
            cacheCreation1hTokens: rollup.cacheCreation1hTokens,
            reasoningOutputTokens: rollup.reasoningOutputTokens,
            providerActiveDurationMs: rollup.providerActiveDurationMs,
            toolDurationMs: rollup.toolDurationMs,
            coverage: rollup.coverage,
            ...(Array.isArray(rollup.missingRanges) &&
            rollup.missingRanges.length
              ? { missingRanges: rollup.missingRanges.slice(0, 200) }
              : {}),
          };
          deps.writeErr(
            "submitting the host's last usage snapshot from the retained spool",
          );
        }
      } catch {
        // No snapshot — the session closes with whatever the server holds.
      }
      const result = await call(caller, "complete_agent_session", {
        sessionId,
        outcome: "COMPLETED",
        endBranch: sameRepo?.branch ?? null,
        endHead: sameRepo?.head ?? null,
        endDirty: sameRepo?.dirty ?? null,
        ...(spooledUsage ? { usage: spooledUsage } : {}),
        // Evidence floor (§5/§6): the CLI-counted commits in the range feed
        // E2 and the summary's density line; the acknowledge flag closes over
        // unmet checks with each stamped MISSING into Review readiness.
        ...(commitCount !== null ? { commitCount } : {}),
        ...(flags.acknowledgeEvidenceGaps
          ? { acknowledgeEvidenceGaps: true }
          : {}),
        expectedUpdatedAt: session.updatedAt,
      });
      if (inspection) {
        clearAlignmentMarker(deps.configPath, inspection.root, sessionId);
      }
      const verdict = sessionCloseVerdict(
        result,
        (session.alignment as { capture?: string } | null)?.capture === "off",
      );
      deps.writeOut(
        flags.json
          ? JSON.stringify(result)
          : `Session ${sessionId} closed · capture ${verdict.capture} · summary ${result.summaryArtifactId ? String(result.summaryArtifactId) : "—"}`,
      );
      // `complete_agent_session` answers lifecycle fields only — it carries
      // no `usage`, so reading it here printed NO TOKEN TELEMETRY over a
      // close that had just submitted the spool's snapshot. The verdict must
      // read the authoritative post-close row instead.
      const closed = await call(caller, "get_agent_session", {
        sessionId,
      }).catch(() => null);
      reportTelemetry(closed ?? result);
      return verdict.code;
    });
  } catch (error) {
    return reportError(error, deps);
  }
}
